/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Desktop;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.CsvSource;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
    
    
    @Test void appAdd() {
        App classTest = new App();
        assertEquals(11, classTest.add(5,6), "PASS");
    }

@ParameterizedTest(name = "{0} + {1} = {2}")
@CsvSource({
	"0,1,1",
	"1,2,3",
	"49,51,100"})
void add(int first, int second, int expected) {
    App classTest2 = new App();
	assertEquals(expected, classTest2.add(first, second), ()-> first +"+" + second + "should equals"+ expected);
}
}